### PR TITLE
feat(hydrated_bloc): use user provided storage in hydrated cubit

### PR DESCRIPTION
**Pull request by Elias8**
## Status

**READY**

## Breaking Changes

NO

## Description

- Resolves [[Feature Request] Hydrated blocs with different storages in the same app #1421](https://github.com/felangel/bloc/issues/1421)  as I suggested the implementation in the comment

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by dolsem** [comment]
Any status update on this? Would be great to have this feature!

**Comment by felangel** [comment]
Rather than injecting a storage into specific blocs I'd prefer to experiment with a `HydratedStorageProvider` that scopes different storage implementations to different parts of the widget tree. I was planning to revisit this within the next week or so (once v7.2.0 is out and a v8.0.0-dev release is published).

**Comment by Elias8** [comment]
@felangel I think that is a better approach! 👍

**Comment by felangel** [comment]
Closing this PR for now in favor of the `HydratedStorageProvider` approach. I'll try to get to this in the next few days as part of the v8.0.0 release 👍

**Comment by felangel** [comment]
> @felangel would it be possible to use multiple storage providers with different blocs within the same widget? My use case is using flutter_secure_storage for auth tokens (auth cubit), and default storage for all other app data.

In that particular case you'd need to split the auth cubit BlocProvider into its own widget but I also don't recommend managing auth tokens in cubits/blocs. In my opinion, those should be managed by the networking layer using something like [fresh_dio](https://pub.dev/packages/fresh_dio). Hope that helps 👍

**Comment by dolsem** [comment]
@felangel I see, interesting. I'll give fresh_dio a try, thanks!

**Pull request closed without merging**
