### PR TITLE
docs: updates to zh-cn documentation

### PR DESCRIPTION
**Pull request by jakecastelli**
## Status

**Ready**

## Breaking Changes

NO

## Description

Update zh-cn docs for introduction part. See more at #1628

## Type of Change

- [x] 📝 Documentation

### CODE REVIEW

**Comment by felangel** [comment]
@jakecastelli thanks so much for the contributions! Do you still want to keep this on hold or would it be okay to merge this as is and open separate pull requests for the remaining docs?

**Comment by jakecastelli** [comment]
> @jakecastelli thanks so much for the contributions! Do you still want to keep this on hold or would it be okay to merge this as is and open separate pull requests for the remaining docs?

Hi Felix, could you please hold this PR just a little bit longer? I haven't finished the intro part yet, I have been swamped recently, but I will come back to this PR as fast as I can, cheers.

**Comment by jakecastelli** [comment]
Hi Flex, the only part left in Intro for now is migration, I will make sure to cover that part once I have some time.

**Review by felangel — APPROVED** [review]
LGTM! Thanks so much for the contribution! I really appreciate it 🙏 💯 🚀

**Pull request merged**
