### PR TITLE
feat(flutter_todos): Add firestore backend. Support compile time API selection.

### PR DESCRIPTION
**Pull request by maximveksler**
## Status

**WIP** Looking for help in implementing unit test coverage.

## Breaking Changes

NO

## Description

Adding Firestore support into the Todos example.

https://github.com/felangel/bloc/pull/2859 introduced a Well-Architected todos example, however in doing so dropped Firestore support.

A [comment](https://github.com/felangel/bloc/pull/2859#issuecomment-1041286518) by @jeroen-meijer shows that there is interest by the community to see an elegent Firestore integration in the todos example.

> Regarding adding Firestore support; thank you so much for working on this. One thing to note is, last time I spoke to @felangel, I believe we agreed that adding a whole separate project with a Firestore implementation might be a bad idea, since it adds a lot of code duplication and maintainer overhead.

This PR implements the requirment of no code duplication, leaving the choice of which implementation ot use  to the developer.

* `local storage` remains the default out of the box implemenation.
* `firestore` usage is documented in `docs/firestore/README.md`

`packages/firestore_todos_api` is cherry picked from the work done by @Gene-Dana in  [feat/flutter-todos-firestore](https://github.com/felangel/bloc/tree/feat/flutter-todos-firestore) branch.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by Gene-Dana** [comment]
HI there ! I was just awaiting feedback on the tests that we implemented

**Comment by maximveksler** [comment]
> HI there ! I was just awaiting feedback on the tests that we implemented

Hey @Gene-Dana I'm happy to collaborate on providing feedback on existing tests, and implementing todos_api_factory tests. 

I will be getting to that obviously; however given that I still have some millage to cover with in Dart & Flutter  learning I believe it will take me a week or 2 before I can close the loop on that.  

Happily accepting contributions!

**Comment by Gene-Dana** [comment]
Also, there is an issue with the ordering. In the original local storage API there the todos are stored in a list and the orders is preserved. In Firestore, this is not the case, and so I simply added a timestamp as the ID. Not sure this is the worlds best implementation and was looking for feedback regarding this.


> implementing todos_api_factory tests.

What do you mean by this?

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 hoping everything is okay. Haven't received any feedback on the way that the tests were written !

**Comment by Gene-Dana** [comment]
Hey there @maximveksler just checking in if there was any feedback you or @felangel could offer

**Comment by maximveksler** [comment]
Adding [help wanted](https://github.com/felangel/bloc/labels/help%20wanted) here would be great.

I do see myself getting back to working on this in the forseeable future, however would be glad to push it forward.

Implementation is DONE, however test coverage is lacking.

**Comment by Gene-Dana** [comment]
@felangel reviews please !

**Comment by Gene-Dana** [comment]
Hi there @maximveksler, I'm seeking to understand your approach with the `TodosApiFactory`

 Originally when I spoke with @felangel about implementing this he suggested that we created separate `main's for the `firestore_todos_api`

Like this:
image


```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firestore_todos_api/firestore_todos_api.dart';
import 'package:flutter_services_binding/flutter_services_binding.dart';
import 'package:flutter_todos/bootstrap.dart';
import 'package:flutter_todos/firebase_options.dart';

Future<void> main() async {
  FlutterServicesBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  final todosApi = FirestoreTodosApi(firestore: FirebaseFirestore.instance);

  bootstrap(todosApi: todosApi);
}

```

Is there any distinct advantages to the factory besides reducing the number of files? I thought @felangels approach was intuitive

**Comment by maximveksler** [comment]
Hey @Gene-Dana 

I belive that the approach of having several mains leads to code duplication, and IMHO is less aestetic.

The usage of a single main seems to be more generally suitable case for introduction into real life applications.

Therefore I've used the `--dart-define` approach, thus allowing to dynamically switch during build time between backedns (for example for the cases of CI vs Staging builds).

The single main is introduced with the default being the current (local storage) implementation, which allows me to intorudce the change in a backwords compatible fashion for the `example` users.

Please let me know if that ansawers you question, happy to have the solution architecture discussion.

**Comment by felangel** [comment]
This is very old and outdated and not ready to merge unfortunately. Going to close this for now since it's not a high enough priority but if anyone feels motivated and wants to work on this let me know 👍

**Pull request closed without merging**
