### PR TITLE
docs(flutter_weather) general updates

### PR DESCRIPTION
**Pull request by definitelyokay**
## Status

**READY**

## Breaking Changes

NO

## Description

Because flutter_weather uses cubit, there wasn't a change to the code in the documentation. Instead, I took the time I would have spent doing that and applied it toward cleaning up the snippets and linking to actual code wherever possible for the `pubspec.yaml` and `build.yaml` files, since those can get out of sync quickly (the former more so than the latter).

I also made some wording changes and updated the structure slightly so that including the pubspec's up front would make sense, rather than building them up gradually. If I missed something or it doesn't seem cohesive, I will happily fix it.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by definitelyokay** [comment]
I'm a little worried that this thinks I changed 80 files...I don't know what happened :O I would love some help figuring out how to fix this since it thinks I'm already up to date (I just rebased off master with 0 conflicts).

**Comment by felangel** [comment]
> I'm a little worried that this thinks I changed 80 files...I don't know what happened :O I would love some help figuring out how to fix this since it thinks I'm already up to date (I just rebased off master with 0 conflicts).

I think you just need to edit the pull request to target merging into the v8 branch instead of master.

**Comment by definitelyokay** [comment]
> I think you just need to edit the pull request to target merging into the v8 branch instead of master.

@felangel hmm, I don't see a branch for 8

**Comment by felangel** [comment]
> > I think you just need to edit the pull request to target merging into the v8 branch instead of master.
> 
> @felangel hmm, I don't see a branch for 8

It’s https://github.com/felangel/bloc/pull/2577

**Comment by definitelyokay** [comment]
> It’s #2577

Oh, right 🤦‍♀️

**Comment by definitelyokay** [comment]
ugh, still a lot of conflicts—really weirded out cuz i haven't touched those files AFAIK :O

**Comment by felangel** [comment]
> ugh, still a lot of conflicts—really weirded out cuz i haven't touched those files AFAIK :O

Maybe try closing this PR and opening a new one where you cherry pick the individual commits you want?

**Comment by felangel** [comment]
@definitelyokay I cherry-picked and rebased the changes on top of the v7.2.0 branch so don't worry about handling the merge conflicts 👍

**Comment by definitelyokay** [comment]
@felangel thank you—just seeing this

**Pull request closed without merging**
