### PR TITLE
add bloc state subscription to architecture section

### PR DESCRIPTION
**Pull request by AhmedMozaly**
## Status
**READY**

## Breaking Changes
NO

## Description
Add new content about bloc state subscription to architecture section in documentation.

## Todos
- [X] Tests
- [X] Documentation
- [X] Examples

### CODE REVIEW

**Comment by AhmedMozaly** [comment]
@felangel I'v fixed the spacing issue and squashed commits, kindly check

**Comment by AhmedMozaly** [comment]
@felangel I've fixed the spacing issue & also revised the sample code
waiting your feedback

P.S: commits are squash into only one

**Comment by felangel** [comment]
@AhmedMozaly thanks! 💯

**Comment by AhmedMozaly** [comment]
@felangel will this appear in public docs website soon?

**Comment by felangel** [comment]
Yup it should be up right now [link](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication). I made a few minor updates let me know what you think? Thanks so much for the contribution! 🎉

**Comment by AhmedMozaly** [comment]
Cool, I liked the final version a lot
This should make it clear for how blocs can communicate

Thanks a lot for your consideration

**Pull request merged**
