### PR TITLE
docs: Add persian(fa) translation

### PR DESCRIPTION
**Pull request by mbfakourii**
## Status

**READY**

The following tasks must be completed.

- [x] testing.mdx
- [x] naming-conventions.mdx

## Breaking Changes

NO

## Description

Translates the document to persian(fa).

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
@mbfakourii thanks for the contributions! Is this ready to merge? I think it'd be good to keep merging smaller PRs to avoid merge conflicts and to deploy incremental improvements that developers can benefit from.

**Comment by mbfakourii** [comment]
> @mbfakourii thanks for the contributions! Is this ready to merge? I think it'd be good to keep merging smaller PRs to avoid merge conflicts and to deploy incremental improvements that developers can benefit from.

OK, I think it's ready

**Comment by felangel** [comment]
> > @mbfakourii thanks for the contributions! Is this ready to merge? I think it'd be good to keep merging smaller PRs to avoid merge conflicts and to deploy incremental improvements that developers can benefit from.
> 
> OK, I think it's ready

Awesome, I'll review and merge this tomorrow. Thanks again for all your contributions! 💙

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contributions! 💙

**Pull request merged**
