### PR TITLE
Czech docs w/o Tutorials

### PR DESCRIPTION
**Pull request by tenhobi**
## Status
**IN DEVELOPMENT**

## Breaking Changes
NO

## Description

Translation of the docs to the Czech language.

I am sticking with the `cs` lang code, not `cs-cz`, because the language is not used outside Czechia. So to make it simple. 😃 

## Todos

* [x] README
* [x] Cover page
* [x] Sidebar
* Introduction
  * [x] Getting Started
  * [x] Why Bloc?
* Core Concepts
  * [x] bloc
  * [x] flutter_bloc
* [x] Architecture
* [x] Testing
* ~Tutorials~
  * Flutter
    * [x] Counter
    * [ ] Timer
    * [ ] Infinite List
    * [ ] Login
    * [ ] Weather
    * [ ] Todos
    * [ ] Firebase Login
    * [ ] Firestore Todos
  * AngularDart
    * [ ] Counter
  * Flutter + AngularDart
    * [ ] Github Search
* Recipes
  * Flutter
    * [x] Show SnackBar
    * [x] Navigation
    * [x] Bloc Access
* Tools
  * Extensions
    * [x] IntelliJ
    * [x] VSCode

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```
cd docs &&  python -m SimpleHTTPServer 8080 .
```

### CODE REVIEW

**Comment by felangel** [comment]
@tenhobi I see you're flying through the docs 😄 Let me know when you'd like me to review. You can always open separate pull requests for individual sections if you don't have the time to do everything at once 👍

**Comment by tenhobi** [comment]
> Because every state change is recorded, we are able to very easily instrument our applications and track all user interactions & state changes in one place.

@felangel What is meant by `instrument`?

**Comment by felangel** [comment]
> > Because every state change is recorded, we are able to very easily instrument our applications and track all user interactions & state changes in one place.
> 
> @felangel What is meant by `instrument`?

I meant we can easily attach any third party plugin for analytics/reporting. You can check out https://en.wikipedia.org/wiki/Instrumentation_(computer_programming) for more context 👍

**Comment by tenhobi** [comment]
@felangel I am done with translations (except tutorials, I will do them ). 🎉

**Comment by felangel** [comment]
> @felangel I am done with translations (except tutorials, I will do them sometimes later). 🎉
> 
> There might be some misspelling, but I cannot find any issues. So response from community must enoug. 🙂

You’re awesome! I’ll review the changes later today. Thanks again 💯

**Pull request merged**
