### PR TITLE
PT-BR Docs

### PR DESCRIPTION
**Pull request by henriquearthur**
## Status
**READY**

## Breaking Changes
NO

## Description
Translating docs to PT-BR

## Todos
- [ ] README
- [x] Cover page
- [x] Sidebar

* Introduction
  * [x] Getting Started
  * [x] Why Bloc?
  * Core Concepts
    * [ ]  bloc
    * [ ]  flutter_bloc
  * [ ]  Architecture
  * [ ]  Testing

* Tutorials
  * Flutter
    * [ ]  Counter
    * [ ]  Timer
    * [ ]  Infinite List
    * [ ]  Login
    * [ ]  Weather
    * [ ]  Todos
    * [ ]  Firebase Login
    * [ ]  Firestore Todos

  * AngularDart
    * [ ]  Counter

  * Flutter + AngularDart
    * [ ]  Github Search

* Recipes
  * Flutter
    * [ ]  Show SnackBar
    * [ ]  Navigation
    * [ ]  Bloc Access

* Tools
  * Extensions
    * [ ]  IntelliJ
    * [ ]  VSCode

### CODE REVIEW

**Comment by henriquearthur** [comment]
@felangel there are some people in brazilian community who wants to help translating this package.

Should I tell them to do PRs on my fork so we can keep 1 PR or do you want to merge my PR so they can create subsequent PRs?

**Comment by felangel** [comment]
> @felangel there are some people in brazilian community who wants to help translating this package.
> 
> Should I tell them to do PRs on my fork so we can keep 1 PR or do you want to merge my PR so they can create subsequent PRs?

I’m fine with either one. If you’re happy with what you have so far we can merge it otherwise you can add them as collaborators and then can work off your branch.

**Comment by ngdevsousa** [comment]
@henriquearthur lets keep just one PR. I'll fork your project

**Comment by henriquearthur** [comment]
> @henriquearthur lets keep just one PR. I'll fork your project

I added you as collaborator. Just commit to the `pt-br` branch,

**Comment by rodriguesJeff** [comment]
Hello brother. Have a possibility that i contribute with the translation? I've open a issue asking it, but now i saw that you already are translating...

**Comment by felangel** [comment]
@henriquearthur can you please add @rodriguesJeff as a collaborator? Also, it might be better to start merging the work you’ve finished to make it easier to others to tackle smaller parts of the documentation. We don’t have to finish the whole thing in one PR imo. Thoughts?

**Comment by henriquearthur** [comment]
> @henriquearthur can you please add @rodriguesJeff as a collaborator? Also, it might be better to start merging the work you’ve finished to make it easier for others to tackle smaller parts of the documentation. We don’t have to finish the whole thing in one PR imo. Thoughts?

I have some unpushed commits at home I will push later today and mark this PR as ready. Will also check with @ngdevsousa if he has progress to merge.

I agree with you, let's merge this and continue to work on the translation with other PRs, it will be better for other people to contribute.

**Comment by rodriguesJeff** [comment]
When i can start to contribute?

**Comment by felangel** [comment]
@rodriguesJeff you can start now. Just fork the repo and you can start from the bottom of the checklist and work your way up until @henriquearthur merges. Let me know if that helps 👍

**Comment by henriquearthur** [comment]
I'm okay with merging this now. I will continue to work on the translation and create more PRs.

This PR translates:
- [x] README _(partial)_
- [x] Cover page
- [x] Sidebar
- [x] Getting Started
- [x] Why Bloc?
- [x]  Testing

**Pull request merged**
