### PR TITLE
docs: Add persian(fa) translation

### PR DESCRIPTION
**Pull request by mbfakourii**
## Status

IN DEVELOPMENT

The following tasks must be completed (13/26)

- [x] _coverpage.md
- [x] _sidebar.md
- [x] angularcountertutorial.md
- [x] architecture.md
- [x] blocintellijextension.md
- [x] blocnamingconventions.md
- [x] blocvscodeextension.md
- [x] coreconcepts.md
- [x] whybloc.md
- [x] testing.md
- [x] recipesfluttershowsnackbar.md
- [x] gettingstarted.md
- [x] recipesflutternavigation.md
- [x] fluttercountertutorial.md
- [ ] fluttertimertutorial.md
- [ ] flutterinfinitelisttutorial.md
- [ ] recipesflutterblocaccess.md
- [ ] flutterfirebaselogintutorial.md
- [ ] faqs.md
- [ ] flutterlogintutorial.md
- [ ] flutterbloccoreconcepts.md
- [ ] flutterangulargithubsearch.md
- [ ] fluttertodostutorial.md
- [ ] flutterweathertutorial.md
- [ ] migration.md
- [ ] README.md

## Breaking Changes

NO

## Description

Translates the document to persian(fa).

## Type of Change

- 📝 Documentation

### CODE REVIEW

**Comment by felangel** [comment]
@mbfakourii thanks so much for this! Let me know whenever you think this is ready for review

**Comment by mbfakourii** [comment]
> @mbfakourii thanks so much for this! Let me know whenever you think this is ready for review

Yes, Sure

**Comment by felangel** [comment]
@mbfakourii would you like me to review and try to merge what you've done so far? It might be good to break this up into smaller PRs to provide incremental value to the community. Let me know what you think, thanks!

**Comment by mbfakourii** [comment]
> @mbfakourii would you like me to review and try to merge what you've done so far? It might be good to break this up into smaller PRs to provide incremental value to the community. Let me know what you think, thanks!

No, I want to continue. I was busy a few days ago.

**Comment by felangel** [comment]
@mbfakourii this is quite outdated (it's still using the old docs site). I'd really love to get these merged in but I think the best thing to do would be to close this PR and open a new PR moving one doc at a time to the new docs site. Let me know if there's anything I can do to help and apologies for any inconvenience!

**Comment by mbfakourii** [comment]
> @mbfakourii this is quite outdated (it's still using the old docs site). I'd really love to get these merged in but I think the best thing to do would be to close this PR and open new PRs moving one doc at a time to the new docs site. Let me know if there's anything I can do to help and apologies for any inconvenience!

No, no problem, I will open a new PR as soon as possible.

**Comment by mbfakourii** [comment]
> @mbfakourii this is quite outdated (it's still using the old docs site). I'd really love to get these merged in but I think the best thing to do would be to close this PR and open new PRs moving one doc at a time to the new docs site. Let me know if there's anything I can do to help and apologies for any inconvenience!

It seems that none of the translated files are available in the [new doc](https://github.com/felangel/bloc/tree/master/docs/src/content/docs). Has a new document been written?

**Comment by felangel** [comment]
> > @mbfakourii this is quite outdated (it's still using the old docs site). I'd really love to get these merged in but I think the best thing to do would be to close this PR and open new PRs moving one doc at a time to the new docs site. Let me know if there's anything I can do to help and apologies for any inconvenience!
> 
> It seems that none of the translated files are available in the [new doc](https://github.com/felangel/bloc/tree/master/docs/src/content/docs). Has a new document been written?

The docs site was heavily revamped but most of the content should be similar so you can just open one PR at a time adding your translations in.

**Pull request closed without merging**
