### PR TITLE
feat(intelliJ): wrap with - quick action snippet

### PR DESCRIPTION
**Pull request by mzdm**
## Status

**IN DEVELOPMENT**

## Description

This is an initial implementation of #2150, a rewrite of VS Code part 👌
Features left to be made are marked as **TODOs**

(I'm not really familiar with Kotlin so feel free to refactor afterwards to keep consistency)

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by mzdm** [comment]
@felangel Not sure how to handle multi snippet chooser. In VS Code you have it like this:
image

but in order to do that in IntelliJ pretty much 5 duplicate classes of `IntentionAction` would be needed.

Another solution would be to display it like this (via new pop up menu), which is now implemented:
ext


What do you think?

**Comment by felangel** [comment]
> @felangel Not sure how to handle multi snippet chooser. In VS Code you have it like this:
> image
> 
> but in order to do that in IntelliJ pretty much 5 duplicate classes of `IntentionAction` would be needed.
> 
> Another solution would be to display it like this (via new pop up menu), which is now implemented:
> ext
> 
> What do you think?

it'd be nice to keep it consistent. Would it be possible to create a reusable base class and extend it for each action?

**Comment by mzdm** [comment]
> it'd be nice to keep it consistent. Would it be possible to create a reusable base class and extend it for each action?

The extension class looks like this `public class BlocWrapIntentionAction extends PsiElementBaseIntentionAction implements IntentionAction {...}` so it already extends 1 class and cannot another. So I don't know what be an alternative approach to this to avoid code duplication

**Comment by felangel** [comment]
@mzdm ill take a closer look shortly and see what I can come up with. Thanks so much for taking the lead on this 🙏

**Comment by mzdm** [comment]
it's now more consistent with the other PR (instead of removing the key it selects the `Subject` part)

what's now left is solve how to handle "Wrap with menu". I didn't find a way to have all in the same menu and in the same Java class (so each `Intention` class for each Intention action is probably needed)

possible room for improvement: the "Wrap with.." when triggered via Alt+Enter is sometimes displayed outside widget tree (class names, methods, ...). (in live templates there's API within XML files for it, so still figuring out this)

**Comment by mzdm** [comment]
A minor bug I've encountered:

sometimes wrapping splits the widget in half (happens also in VsCode) - usually with the top most widget in the widget tree.

example from https://github.com/felangel/bloc/blob/master/examples/flutter_counter/lib/counter/view/counter_view.dart:
[before](https://user-images.githubusercontent.com/67197047/111655563-0cc1a580-880a-11eb-9d6f-cd76d834b8e0.png)
[after](https://user-images.githubusercontent.com/67197047/111655736-2cf16480-880a-11eb-9cc4-73cbd5ced1fb.png)

**Comment by felangel** [comment]
> A minor bug I've encountered:
> 
> sometimes wrapping splits the widget in half (happens also in VsCode and so in IntelliJ because the selection logic is the same) - usually with the top most widget in the widget tree.
> 
> example from https://github.com/felangel/bloc/blob/master/examples/flutter_counter/lib/counter/view/counter_view.dart:
> [before](https://user-images.githubusercontent.com/67197047/111655563-0cc1a580-880a-11eb-9d6f-cd76d834b8e0.png)
> [after](https://user-images.githubusercontent.com/67197047/111655736-2cf16480-880a-11eb-9cc4-73cbd5ced1fb.png)

yup I'm aware of that issue and just haven't had time to fix it yet. Since it's consistent with vscode I think it's ok unless you have time to investigate further and get a fix 👍

**Comment by felangel** [comment]
@mzdm is this ready for review now?

**Comment by mzdm** [comment]
> @mzdm is this ready for review now?

Yes, should be 👍

**Review by felangel — APPROVED** [review]
LGTM 💯 🚀 💙

**Pull request merged**
