### PR TITLE
feat(bloc_concurrency): sequentialDroppable transformer

### PR DESCRIPTION
**Pull request by feduke-nukem**
Added new kind of transformer which was requested in #3435.  

## Status

**READY**

## Breaking Changes

NO

## Description

The main point is that sometimes we need to drop certain events in sequential order by type. Once I faced this problem myself and other people also asked about it, so I decided to create a solution.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by karvulf** [comment]
Just saw this at crashlytics using your implementation:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Cannot add new events while doing an addStream
       at _BroadcastStreamController.close(dart:async)
       at _SequentialAndDroppable.bind.<fn>(notification_uebersicht_bloc.dart:388)
```

Probably an issue using this.

@feduke-nukem

**Comment by feduke-nukem** [comment]
> Just saw this at crashlytics using your implementation:
> 
> ```
> Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Cannot add new events while doing an addStream
>        at _BroadcastStreamController.close(dart:async)
>        at _SequentialAndDroppable.bind.<fn>(notification_uebersicht_bloc.dart:388)
> ```
> 
> Probably an issue using this.
> 
> @feduke-nukem

I'll check, thanks.

**Comment by feduke-nukem** [comment]
> Just saw this at crashlytics using your implementation:
> 
> ```
> Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Cannot add new events while doing an addStream
>        at _BroadcastStreamController.close(dart:async)
>        at _SequentialAndDroppable.bind.<fn>(notification_uebersicht_bloc.dart:388)
> ```
> 
> Probably an issue using this.
> 
> @feduke-nukem

Could you provide more detailed information?

**Comment by karvulf** [comment]
Currently not, because I just saw that on crashlytics but I can't say how that happened. If this happen again and I have more nformation Ill come back @feduke-nukem

**Comment by felangel** [comment]
Closing this for now since folks can implement this in their own codebases if needed. Happy to revisit this in the future.

**Pull request closed without merging**
