### PR TITLE
fix(hydrated_bloc): traverse state and fix maps

### PR DESCRIPTION
**Pull request by orsenkucher**
## Status

**READY** (tests missing)

## Breaking Changes

NO

## Description

closes https://github.com/felangel/bloc/issues/1452

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by orsenkucher** [comment]
@felangel https://github.com/felangel/bloc/pull/1456 incorporates this

**Comment by orsenkucher** [comment]
:partying_face:Closing in favor of better #1456

**Comment by orsenkucher** [comment]
reopen for now

**Comment by felangel** [comment]
@orsenkucher why did we reopen this? Isn't it covered by #1456?

**Comment by orsenkucher** [comment]
Yup, closing it again

**Pull request closed without merging**
