### PR TITLE
[gettingstarted.md] translation to Azerbaijani

### PR DESCRIPTION
**Pull request by KenanYusubov**
**Gettingstarted.md is translated to Azerbaijani.**

### CODE REVIEW

**Comment by Classy-Bear** [comment]
You should only submit the translated files.

**Comment by felangel** [comment]
@KenanYusubov as @Classy-Bear mentioned, can you please only include the translated files? Thanks!

**Comment by felangel** [comment]
@KenanYusubov I've done this initial setup for Azerbaijani support and I included your `gettingstarted.md` changes. Going to close this PR and now you should be good to go for subsequent PRs 👍

**Comment by KenanYusubov** [comment]
Sorry for my bad Github experience. It is first time that I translate something to my language. I ll correct it. Thanks a lot for help @Classy-Bear  and @felangel.

**Pull request closed without merging**
