### PR TITLE
docs: add `fa/index.mdx`, `fa/getting-started.mdx`, and `fa/why-bloc.mdx`

### PR DESCRIPTION
**Pull request by mbfakourii**
## Status

**READY**

## Breaking Changes

NO

## Description

Translates the document to persian(fa).

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by mbfakourii** [comment]
cc @felangel

**Comment by mbfakourii** [comment]
cc @felangel

**Comment by mbfakourii** [comment]
@felangel 

I think it's ready to merge, can you check it?

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contributions! 💙

**Comment by mbfakourii** [comment]
@felangel 

A series of persian language translations have been improved in the new `starlight`, if you could upgrade `starlight` to the latest version.

**Pull request merged**
