### PR TITLE
Spanish Translation: FAQ, Beginner Tutorials, Intermediate Tutorials and fixing small details

### PR DESCRIPTION
**Pull request by Classy-Bear**
## Status
**READY**

## Breaking Changes
NO

## Description
* Adding `faqs.md` to `_sidebar.md`.
* Changing ">" to "?>" in `blocnamingconvetions.md` and `testing.md` (English documentation has it like this "?>").
* Translating `faqs.md` to Spanish.
* Adding a grammar article to `gettingstarted.md` for more readability. 
* Making the title in `testing.md` to match the `_sidebar.md`.
* Translating comments in `testing.md`.
* Translating beginner and intermediate tutorials
## File changed in this PR
- [ ] README
- [ ] Cover page
- [x] Sidebar
- Introduction
  - [x] Getting Started
  - [ ] Why Bloc?
- Core Concepts
  - [ ] bloc
  - [ ] flutter_bloc
- [ ] Architecture
- [x] Testing
- [x] Naming Conventions
- [x] FAQs
- Tutorials
  - Flutter
    - [x] Counter
    - [x] Timer
    - [x] Infinite List
    - [x] Login
    - [ ] Weather
    - [ ] Todos
    - [ ] Firebase Login
    - [ ] Firestore Todos
  - AngularDart
    - [ ] Counter
  - Flutter + AngularDart
    - [ ] Github Search
- Recipes
  - Flutter
    - [ ] Show SnackBar
    - [ ] Navigation
    - [ ] Bloc Access
- Tools
  - Extensions
    - [ ] IntelliJ
    - [ ] VSCode

### CODE REVIEW

**Comment by Classy-Bear** [comment]
In the Tutorial section I didn't translate H1 and H2 titles that are related to class names of the code snippets for example. To explain this better I will use the Counter tutorial.

<details>
<summary>I use this</summary>

## CounterEvent

```dart
enum CounterEvent { increment, decrement }
```
</details>

<details>
<summary>instead of this</summary>

## Translated title

```dart
enum CounterEvent { increment, decrement }
```
</details>

<details>
<summary>but the ones that didn't have a reference to any class I translated it</summary>

## Translated title
Since our counter's state can be represented by an integer we don't need to create a custom class!

*The following example is from the Action section of the [Timer tutorial](https://bloclibrary.dev/#/fluttertimertutorial?id=actions).*

If you want fine-grained control over when the `builder` function is called you can provide an optional `condition is translated` to `BlocBuilder`. The `condition is translated` takes the previous bloc state and current bloc state and returns a `boolean is translated`. If `condition is translated` returns `true is translated`, `builder` will be called with `state is translated` and the widget will rebuild. If `condition is translated` returns `false is translated`, `builder` will not be called with `state is translated` and no rebuild will occur.

**`builder` is not translated because is a function name. `BlocBuilder` is not translated because is a class name.**
</details>

**Comment by felangel** [comment]
@Classy-Bear thanks so much! Let me know when you'd like me to review 👍

**Comment by Classy-Bear** [comment]
> @Classy-Bear thanks so much! Let me know when you'd like me to review 👍

Nice, just give me 2 or 3 days to translate the intermediate tutorials :)

**Comment by Classy-Bear** [comment]
Ok @felangel I'm done, Intermediate Tutorials are translated :)

**Comment by Classy-Bear** [comment]
I will continue with the advanced tutorials in a few weeks, now I am very busy trying to make a portfolio in Flutter to get a job, in these difficult times it is so stressful to find a client or a remote job.

**Comment by felangel** [comment]
> I will continue with the advanced tutorials in a few weeks, now I am very busy trying to make a portfolio in Flutter to get a job, in these difficult times it is so stressful to find a client or a remote job.

No problem and best of luck! Let me know if there's anything I can do to help 👍

**Pull request merged**
