### PR TITLE
feat(flutter_bloc): Add child constructor to BlocBuilder, BlocConsumer and BlocSelector

### PR DESCRIPTION
**Pull request by mahdi739**
## Status

**READY**

## Breaking Changes

NO

## Description

It adds a named constructor to BlocBuilder, BlocConsumer and BlocSelector called "child".
This constructor has an extra parameter called "child" which is a widget that won't be rebuilt during state changes. 
Also, in this constructor you need to use "builderChild" instead of "builder" function which provides you that pre-built child to place in widget-tree.

It's good for when a part of widget tree doesn't depend on the state and can't be created outside of the BlocBuilder. (Like when you want to change color of container but not its child)
The good point is that we don't have to refactor our old code and we can use the default constructor as well.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by mahdi739** [comment]
@felangel 
Hello Mr. Angelov 👋
Yes it's pretty similar and both have same purpose. 
But the main difference is that I created a named constructor (instead of modifying default constructor) so there's no need to refactoring old codes. No one have to even know about this change, just whoever need this option can use it.

**Comment by felangel** [comment]
> @felangel Hello Mr. Angelov 👋 Yes it's pretty similar and both have same purpose. But the main difference is that I created a named constructor (instead of modifying default constructor) so there's no need to refactoring old codes. No one have to even know about this change, just whoever need this option can use it.

Can you provide a real-world example of when you'd use `child`? I'm not sure I understand when this type of optimization would be beneficial. It makes sense for widgets like `AnimatedBuilder` because you are dealing with animations but I'm not convinced it makes sense in the context of bloc. In addition, you can always create your own widget that wraps `BlocBuilder` to apply this change and I'd prefer not to include this unless there's a very strong argument in its favor. Let me know what you think, thanks!

**Comment by mahdi739** [comment]
> 
> Can you provide a real-world example of when you'd use `child`? I'm not sure I understand when this type of optimization would be beneficial. It makes sense for widgets like `AnimatedBuilder` because you are dealing with animations but I'm not convinced it makes sense in the context of bloc. In addition, you can always create your own widget that wraps `BlocBuilder` to apply this change and I'd prefer not to include this unless there's a very strong argument in its favor. Let me know what you think, thanks!

In flutter most of things are widgets so they could be separated by its own BlocBuilder. 
BUT there are somethings that are not widget. Like `color` and `decoration` in `Container`, or 
the `opacity` value in `Opacity` widget (like the example in #1752 mentioned)

Or assuming in a stack or column which already have 10 widget and 9 of them needs BlocBuilder but one of them doesn't (and it's really heavy!). In case of separating each one to a separated BlocBuilder, it reduces boilerplate code.

**Comment by felangel** [comment]
> > Can you provide a real-world example of when you'd use `child`? I'm not sure I understand when this type of optimization would be beneficial. It makes sense for widgets like `AnimatedBuilder` because you are dealing with animations but I'm not convinced it makes sense in the context of bloc. In addition, you can always create your own widget that wraps `BlocBuilder` to apply this change and I'd prefer not to include this unless there's a very strong argument in its favor. Let me know what you think, thanks!
> 
> In flutter most of things are widgets so they could be separated by its own BlocBuilder. BUT there are somethings that are not widget. Like `color` and `decoration` in `Container`, or the `opacity` value in `Opacity` widget (like the example in #1752 mentioned)
> 
> Or assuming in a stack or column which already have 10 widget and 9 of them needs BlocBuilder but one of them doesn't (and it's really heavy!). In case of separating each one to a separated BlocBuilder, it reduces boilerplate code.

Can you provide some code snippets that illustrate the scenario you have in mind?

**Comment by mahdi739** [comment]
>
> Can you provide some code snippets that illustrate the scenario you have in mind?

This is a part my code I'm working on it right now:

```
Stack(
                alignment: Alignment.bottomCenter,
                children: [
                  Container(
                    constraints: const BoxConstraints.expand(height: double.infinity),
                    // child: FadeTransition(
                    // opacity: controller.animationFirst,
                    child: controller.firstImageProvider.value,
                  ), //),
                  Container(
                      constraints: const BoxConstraints.expand(height: double.infinity),
                      child: FadeTransition(
                        opacity: controller.animationSecond,
                        child: controller.secondImageProvider.value,
                      )),
                  if (controller.filesController.settingsService.themeIndex.val != 1 &&
                      controller.filesController.settingsService.themeIndex.val != 3)
                    AnimatedContainer(
                      duration: Duration(milliseconds: 300),
                      height: 300,
                      alignment: Alignment.bottomCenter,
                      decoration: BoxDecoration(
                          gradient: LinearGradient(
                              begin: Alignment.bottomCenter,
                              end: Alignment.topCenter,
                              colors: [
                            controller.filesController.realDominantColor.value,
                            controller.filesController.realDominantColor.value.withOpacity(0)
                          ])),
                    ),
                  if (controller.filesController.settingsService.themeIndex.val == 1)
                    Container(
                      color: Colors.black.withOpacity(0.6),
                    ),
                  if (controller.filesController.settingsService.themeIndex.val == 3)
                    Container(
                      color: Colors.white.withOpacity(0.6),
                    ),
                  container,

                  
                ],
              ),
```

(Actually it is already written with another state management but I'm migrating to Bloc. 🙂)

As it shows, the stack has 6 children which 5 of them depend on state but the last one `container` does not (which is my content of page). For now I cached it to a pre-built widget, but it prevent me to make constructor of page `const` and it will become messy if I try to make a separated BlocBuilder for each one.

**Comment by felangel** [comment]
@mahdi739 in the example you provided I recommend specifying a const instance of the child like:

```dart
BlocBuilder<FilesBloc, FilesState>(
              builder: (context, state) {
                return Container(
                  margin: const EdgeInsets.all(10),
                  height: MediaQuery.of(context).size.height * 0.8,
                  width: MediaQuery.of(context).size.width * 0.9,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                    border: Border.all(
                        color: calculateColor(state.imageSource), width: 4),
                    image: DecorationImage(
                        image: FileImage(File(state.imageSource))),
                  ),
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15.0),
                    ),
                    clipBehavior: Clip.antiAlias,
                    child: BackdropFilter(
                      filter: ImageFilter.blur(
                        sigmaX: 20,
                        sigmaY: 20,
                      ),
                      child: const ContentWidget(), //Doesn't depend on state
                    ),
                  ),
                );
              },
            )
```

This will ensure the widget is not rebuilt unnecessarily.

**Comment by mahdi739** [comment]
>
> This will ensure the widget is not rebuilt unnecessarily.

Thank you. Yes but there is some situations that we are not able to use const constructor because that widget doesn't have const constructor or the variables we want to pass it are not constant.
But actually I think if we have this kind of situations, the problem comes from bad coding practices.

**Comment by mahdi739** [comment]
> > > This will ensure the widget is not rebuilt unnecessarily.
> > 
> > 
> > Thank you. Yes but there is some situations that we are not able to use const constructor because that widget doesn't have const constructor or the variables we want to pass it are not constant. But actually I think if we have this kind of situations, the problem comes from bad coding practices.
> 
> Yeah in most cases you should be able to return a const instance. If you have some examples in which thats not possible I’m happy to take a look and discuss alternatives.
> 
> Based on our conversation do you still feel these changes are needed?

This situation occurs mostly when we get some variables from the class and want to pass it to the child widget (that doesn't depend on the state).

for above example it becomes like this:

```
 class ParentWidget extends StatelessWidget {
  const ParentWidget({Key? key, required this.data}) : super(key: key);
  final String data;
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<FilesBloc, FilesState>(
      builder: (context, state) {
        return Container(
          margin: const EdgeInsets.all(10),
          height: MediaQuery.of(context).size.height * 0.8,
          width: MediaQuery.of(context).size.width * 0.9,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15),
            border: Border.all(color: calculateColor(state.imageSource), width: 4),
            image: DecorationImage(image: FileImage(File(state.imageSource))),
          ),
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(15.0),
            ),
            clipBehavior: Clip.antiAlias,
            child: BackdropFilter(
              filter: ImageFilter.blur(
                sigmaX: 20,
                sigmaY: 20,
              ),
              child: ContentWidget(data: data), //Doesn't depend on the state and needs data!
            ),
          ),
        );
      },
    );
  }
}
```


and in another example we have a CheckboxListTile and its value depends on the state but its secondary doesn't. However we can't use const for that:

```
class MyTile extends StatelessWidget {
  const MyTile({
    Key? key,
    required this.height,
    required this.width,
    required this.zentity,
    required this.selectBloc,
    this.onTap,
  }) : super(key: key);
  final double height;
  final double width;
  final Zentity zentity;
  final SelectBloc selectBloc;
  final Function? onTap;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<SelectBloc, SelectState>(
      bloc: selectBloc,
      builder: (context, state) {
        return CheckboxListTile(
          onChanged: (bool? value) {
            //...
          },
          value: state.isSelected,
          secondary: ImageThumb(
            zentity,
            height: height,
            width: width,
          ),//Doesn't depend on the state and needs data!
        );
      },
    );
  }
}
```

According to these examples (and the first example in our conversation which was a column with 6 children) I still think it's needed in this kind of situations.

**Comment by felangel** [comment]
@mahdi739 in that case why not just declare the widget outside the `BlocBuilder` like:

```dart
class MyTile extends StatelessWidget {
  const MyTile({
    Key? key,
    required this.height,
    required this.width,
    required this.zentity,
    required this.selectBloc,
    this.onTap,
  }) : super(key: key);
  final double height;
  final double width;
  final Zentity zentity;
  final SelectBloc selectBloc;
  final Function? onTap;

  @override
  Widget build(BuildContext context) {
    final thumbail =  ImageThumb(
        zentity,
        height: height,
        width: width,
      ),
    );
    return BlocBuilder<SelectBloc, SelectState>(
      bloc: selectBloc,
      builder: (context, state) {
        return CheckboxListTile(
          onChanged: (bool? value) {
            //...
          },
          value: state.isSelected,
          secondary: thumbnail,
      },
    );
  }
}
```

**Comment by mahdi739** [comment]
> @mahdi739 in that case why not just declare the widget outside the `BlocBuilder` like:
> 
> ```dart
> class MyTile extends StatelessWidget {
>   const MyTile({
>     Key? key,
>     required this.height,
>     required this.width,
>     required this.zentity,
>     required this.selectBloc,
>     this.onTap,
>   }) : super(key: key);
>   final double height;
>   final double width;
>   final Zentity zentity;
>   final SelectBloc selectBloc;
>   final Function? onTap;
> 
>   @override
>   Widget build(BuildContext context) {
>     final thumbail =  ImageThumb(
>         zentity,
>         height: height,
>         width: width,
>       ),
>     );
>     return BlocBuilder<SelectBloc, SelectState>(
>       bloc: selectBloc,
>       builder: (context, state) {
>         return CheckboxListTile(
>           onChanged: (bool? value) {
>             //...
>           },
>           value: state.isSelected,
>           secondary: thumbnail,
>       },
>     );
>   }
> }
> ```

Yes it actually does the same thing. So I don't think it's necessary to have an extra child parameter. 
Thank you for helping 🙂

**Pull request closed without merging**
