### PR TITLE
Refactor flutter_bloc to use provider

### PR DESCRIPTION
**Pull request by felangel**
## Status
**READY**

## Breaking Changes
YES

### BlocProvider
- Refactor `BlocProvider` to extend `Provider`
- Rename `BlocProviderTree` to `MultiBlocProvider`

### ImmutableProvider -> RepositoryProvider
- Refactor `ImmutableProvider` to extend `Provider`
- Rename `ImmutableProvider` to `RepositoryProvider`
- Rename `ImmutableProviderTree` to `MultiRepositoryProvider`

### BlocListener
- Rename `BlocListenerTree` to `MultiBlocListener`

### Overall
- Lots of inline documentation updates/improvements

### CODE REVIEW

**Comment by felangel** [comment]
@rrousselGit what do you think?

**Comment by rrousselGit** [comment]
This specific implementation of BlocProvider could be made by subclassing Provider:

```dart
class BlocProvider<T extends Bloc> extends Provider<T> {
  BlocProvider(
    Key key,
    @required ValueBuilder<T> builder,
    Widget child,
  ): super(key: key, builder: builder, child: child, dispose: (_, bloc) => bloc.dispose());

  BlocProvider.value(
    Key key,
    @required T value,
    Widget child,
  ): super.value(key: key, value: value, child: child);

  static T of<T extends Bloc>(BuildContext context) {
    ...
  }
}
```

**Comment by rrousselGit** [comment]
It may be interesting to subclass `MultiProvider` too, to help peoples transition from `BlocProviderTree` and similar.

The mixin shorthand can make it simple:

```dart
mixin _NoOp {}

@Deprecated('Use MultiProvider instead')
class BlocProviderTree = MultiProvider with _NoOp;

@Deprecated('Use MultiProvider instead')
class ImmutableProviderTree = MultiProvider with _NoOp;
```

**Comment by felangel** [comment]
> It may be interesting to subclass `MultiProvider` too, to help peoples transition from `BlocProviderTree` and similar.
> 
> The mixin shorthand can make it simple:
> 
> ```dart
> mixin _NoOp {}
> 
> @Deprecated('Use MultiProvider instead')
> class BlocProviderTree = MultiProvider with _NoOp;
> 
> @Deprecated('Use MultiProvider instead')
> class ImmutableProviderTree = MultiProvider with _NoOp;
> ```

Since the api would already be different (`MultiProvider` takes providers instead of `blocProviders`) I think it might be okay to just call it out as a breaking change.

I'm more concerned about what we're going to do about `BlocListenerTree` since it's not a provider and doesn't make sense to be used within `MultiProvider`.

**Comment by felangel** [comment]
> This specific implementation of BlocProvider could be made by subclassing Provider:
> 
> ```dart
> class BlocProvider<T extends Bloc> extends Provider<T> {
>   BlocProvider(
>     Key key,
>     @required ValueBuilder<T> builder,
>     Widget child,
>   ): super(key: key, builder: builder, child: child, dispose: (_, bloc) => bloc.dispose());
> 
>   BlocProvider.value(
>     Key key,
>     @required T value,
>     Widget child,
>   ): super.value(key: key, value: value, child: child);
> 
>   static T of<T extends Bloc>(BuildContext context) {
>     ...
>   }
> }
> ```

Thanks for the suggestion 👍

Made the change so now the main thing left to work out is how to replace `BlocListenerTree` 💯

**Comment by felangel** [comment]
@axellebot I can definitely make that change. It just didn’t seem like BlocListenerTree was being used when I went around asking developers.

**Pull request merged**
