### PR TITLE
feat(intelliJ): Convert to Multi Widget Action

### PR DESCRIPTION
**Pull request by mzdm**
## Status

**READY**

https://user-images.githubusercontent.com/67197047/126696080-e7986224-33ec-4c2a-b53a-9a2167e3cbac.mp4

## Breaking Changes

NO

## Description

Depends on #2616
Part of #2610

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
@mzdm thanks as always for the amazing contribution! Let me know when you feel this is ready for review and I'm happy to take a look 😄

**Comment by mzdm** [comment]
Should be ready, #2616 should be merged first so it's easier to see the changes

I tested mostly on `flutter_login` example, if there is some issue let me know 👍

**Comment by felangel** [comment]
@mzdm thanks so much for taking the time to make these changes. Looks like after merging #2616 there are some merge conflicts. Let me know if you're able to resolve them or if you'd like me to handle it. Thanks as always! 🙏

**Comment by mzdm** [comment]
> @mzdm thanks so much for taking the time to make these changes. Looks like after merging #2616 there are some merge conflicts. Let me know if you're able to resolve them or if you'd like me to handle it. Thanks as always! 🙏

Done, thanks for taking your precious time to review these PRs!

**Review by felangel — APPROVED** [review]
LGTM! 🎉 🚀

**Pull request merged**
