### PR TITLE
add Jorge Coca's article

### PR DESCRIPTION
**Pull request by braulio94**
## Status
**READY/IN DEVELOPMENT/HOLD**

## Breaking Changes
YES | NO

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Examples

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```
```

## Impact to Remaining Code Base
This PR will affect:

*

### CODE REVIEW

**Comment by felangel** [comment]
Thanks for this however Jorge’s article is just using the bloc pattern and not using the bloc package and I don’t want to include it so that I don’t confuse people.

There all tons of great resources on the bloc pattern however I want to reserve the articles section of the readme to include only articles that reference this package. Let me know if that makes sense.

**Comment by braulio94** [comment]
I totally I understand. There's this package from Andrew: [ReBloc](https://github.com/RedBrogdon/rebloc), would that be a nice candidate?

**Comment by felangel** [comment]
@braulio94 nice candidate for what?

**Comment by braulio94** [comment]
To include in the repo!

**Comment by felangel** [comment]
@braulio94 to include in this repo?
I think that would also be confusing because it is a completely different package with different paradigms.

This repo is home to the bloc, flutter_bloc, and angular_bloc packages. It's not a repo for general bloc architecture/articles. As a result, things in this repo should strictly pertain to the bloc, flutter_bloc, and/or angular_bloc packages.

Does that make sense?
Maybe what you're thinking of belongs in https://github.com/Solido/awesome-flutter?

**Pull request closed without merging**
