### PR TITLE
refactor: clean unnecessary code on FilterButton

### PR DESCRIPTION
**Pull request by guillempuche**
## Status

**READY**

## Breaking Changes

NO

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by marcossevilla** [comment]
hey @guillempuche, it's okay to have parametrized the TextStyles for the private `_Button` widget so if we want to create another button using the private one and customizing it with other TextStyles. What do you think?

**Comment by guillempuche** [comment]
True Marcos.

Sometimes clean is better than coding for a possible future. In [Unix philosophy](http://www.faqs.org/docs/artu/ch01s06.html) there's this:
> Rule of Extensibility: Design for the future, because it will be here sooner than you think. 

But it also says:
> Rule of Simplicity: Design for simplicity; add complexity only where you must. 

I think cleaning it is better for readability of the example. We can *refactor* on the future, instead of predicting.

It's up to you 🙂.

**Comment by marcossevilla** [comment]
> True Marcos.
> 
> Sometimes clean is better than coding for a possible future. In [Unix philosophy](http://www.faqs.org/docs/artu/ch01s06.html) there's this:
> 
> > Rule of Extensibility: Design for the future, because it will be here sooner than you think.
> 
> But it also says:
> 
> > Rule of Simplicity: Design for simplicity; add complexity only where you must.
> 
> I think cleaning it is better for readability of the example. We can _refactor_ on the future, instead of predicting.
> 
> It's up to you 🙂.

I agree with refactoring in the future, but as this already was designed in a way you can create other buttons specifying other TextStyles, it would lead to a rollback to the current implementation if we want to use it later.

So if you agree, I'll close this PR as it's a minor change and the current implementation is simple enough IMO.

What do you think?

**Comment by guillempuche** [comment]
If you want to reuse the button, why making it private? It indicates to me that its purpose is serving the Filter button.

Also, the _Button is very customized for the popup menu of Todos. If you want to be reused in the future, the `PopupMenuItem`, the type `VisibilityFilter` or the tooltip have to receive data from the parent widget, in my understanding. You adapt all the parts (or the important) for the reusability or nothing.

But this is a minor implementation. I close it. Thanks for the dialogue, Marcos 🙂.

**Pull request closed without merging**
