### PR TITLE
feat(flutter_bloc): provide all Multi*Provider parameters in constructor

### PR DESCRIPTION
**Pull request by tynn**
## Status

**READY**

## Breaking Changes

NO (compiletime) / maybe YES (binary)

## Description
Making the child nullable to simplify usage within a _nested_ hierarchy.
Also adding the transition builder for consitency with `MultiProvider`.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Hi @tynn 👋 
Thanks for opening an issue!

Can you please provide a bit more context regarding cases in which having a `TransitionBuilder` is beneficial? I completely understand the argument about maintaining parity with `package:provider` but I also want to make sure I fully understand the use-case we're trying to solve by making this change to the API.

Thanks!

**Comment by felangel** [comment]
> Hej @felangel, parity was actually the only reason. Should I just remove it?
> 
> The issue I had was mostly with `Widget child`, forcing me use `MultiProvider` instead of `MultiBlocProvider` or assume `child!` within a nested hierarchy.

Do you mind providing a short snippet of code to illustrate the issue you're describing? I want to make sure I fully understand, thanks!

**Comment by tynn** [comment]
@felangel could you let me know which parts you'd want to merge? I'll update the PR accordingly or close it then.

**Comment by felangel** [comment]
If the only reason is feature parity I'd highly prefer to keep the API as is because MultiBlocProvider's child should not be optional imo.

**Pull request closed without merging**
