### PR TITLE
Add FAQs to Docs

### PR DESCRIPTION
**Pull request by felangel**
## Status
**READY**

## Breaking Changes
NO

## Description
- Add FAQs section to documentation (#789)

## Todos
- [X] Tests
- [X] Documentation
- [X] Examples

## Impact to Remaining Code Base
- None

### CODE REVIEW

**Comment by tenhobi** [comment]
Hi, you did not add FAQ to the CONTRIBUTING.md list and it seems it's not on the website, is that possible? :-)

**Comment by felangel** [comment]
@tenhobi it should be on the website but you might need to force reload to clear your cache.

**Comment by tenhobi** [comment]
Oh, I see. 😄 

Btw. in https://bloclibrary.dev/#/faqs?id=blocproviderof-fails-to-find-bloc we might also want to add a mention about using `Builder` to access the context?

**Comment by felangel** [comment]
@tenhobi good catch. Will update shortly 👍

**Pull request merged**
