### PR TITLE
fix(intellij): wrapping issues

### LINKED ISSUE #2394: [IntelliJ extension] IDE crashes because of Bloc plugin
**Describe the bug**
My IDE crashes because of a bug in the Bloc plugin. Based on the stack trace I provided down there it's on this [line](https://github.com/felangel/bloc/blob/c94531fa09cd85a4d4318ce48a39c1182b6777e9/extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/intention_action/Utils.java#L35).

**Stack trace**
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.bloc.intellij_generator_plugin.intention_action.Utils.getSelection(Utils.java:35)
	at com.bloc.intellij_generator_plugin.intention_action.BlocWrapWithIntentionAction.isAvailable(BlocWrapWithIntentionAction.java:65)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:153)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:336)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:190)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:335)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:240)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Screenshots**

image

**Additional context**

- Bloc plugin v2.2.0
- IntelliJ IDEA 2021.1 (Community Edition) - Build #IC-211.6693.111, built on April 6, 2021

### PR DESCRIPTION
**Pull request by mzdm**
## Status

**READY**

## Breaking Changes

NO

## Description

Refactor wrapping logic.
Fixes #2394 and cases when the widget was split in a half.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
@mzdm thanks so much for taking the time to address this 💯 
Looks like these changes will also address #2394?

**Comment by mzdm** [comment]
@felangel I noticed that the sorting in the menu is kinda random, do you think it would be better if it was sorted (alphabetically)?

**Comment by mzdm** [comment]
> @felangel I noticed that the sorting in the menu is kinda random, do you think it would be better if it was sorted (alphabetically)?

Nvm seems like that the **order** attribute is not working any way in this case

**Comment by felangel** [comment]
@mzdm I'll review this asap and try to get it merged and published this weekend. Thanks again! 🙏

**Comment by mzdm** [comment]
> @mzdm I'll review this asap and try to get it merged and published this weekend. Thanks again! 🙏

No problem, thanks for the update!

**Review by felangel — APPROVED** [review]
LGTM! 💯 💙 🚀

**Pull request merged**
