### PR TITLE
refactor(angular_bloc)!: use `package:ngdart`

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Breaking Changes

YES

## Description

- refactor(angular_bloc)!: use `package:ngdart`

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [X] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
Hi @felangel, thank you for keeping `angular_bloc` up-to-date! I thought I'd comment here as my idea is more related to `angular_bloc` than `ngdart`.

I'm planning to publish an AngularDart v8 pre-release with the upgraded analyzer this weekend. However, I'd also suggest you publish **one single version** of `angular_bloc` with AngularDart (`ngdart`) v7 that is based on this PR, and after that, publish against the pre-release v8 versions. The reason is that a stable release of AngularDart v8 is probably not coming out in the near future, so this allows the majority of users who are on still on v7 to use `angular_bloc`. In addition, I'm pretty sure your code will work for both v7 and v8, so little if any code changes will be necessary.

However, since (I think) bumping a major version of AngularDart is considered a breaking change, this does means you  have to publish two major versions for `angular_bloc` consecutively, one version for v7, and the next version(s) for v8. What do you think?

Thanks again for your time!

**Comment by felangel** [comment]
> Hi @felangel, thank you for keeping `angular_bloc` up-to-date! I thought I'd comment here as my idea is more related to `angular_bloc` than `ngdart`.
> 
> I'm planning to publish an AngularDart v8 pre-release with the upgraded analyzer this weekend. However, I'd also suggest you publish **one single version** of `angular_bloc` with AngularDart (`ngdart`) v7 that is based on this PR, and after that, publish against the pre-release v8 versions. The reason is that a stable release of AngularDart v8 is probably not coming out in the near future, so this allows the majority of users who are on still on v7 to use `angular_bloc`. In addition, I'm pretty sure your code will work for both v7 and v8, so little if any code changes will be necessary.
> 
> However, since (I think) bumping a major version of AngularDart is considered a breaking change, this does mean you have to publish two major versions for `angular_bloc` consecutively, one version for v7, and the next version(s) for v8. What do you think?
> 
> Thanks again for your time!

Hi @GZGavinZhao 👋 

Thanks so much for maintaining `package:ngdart`!
I'm totally fine publishing a new major version using AngularDart v7 and a prerelease using AngularDart v8 👍 
Will https://github.com/angulardart-community/angular/pull/37 be included as part of AngularDart v7?

**Comment by GZGavinZhao** [comment]
@felangel No, my current plan is that angulardart-community/angular#37 will not be included in AngularDart v7 since it bumps not only a major version of `analyzer` but also a language version. Therefore, I suggest that you publish one new major version using v7 and immediately target v8 afterwards, since judging from this PR it seems like you want to upgrade to Dart 2.19.

**Comment by felangel** [comment]
> @felangel No, my current plan is that [angulardart-community/angular#37](https://github.com/angulardart-community/angular/pull/37) will not be included in AngularDart v7 since it bumps not only a major version of `analyzer` but also a language version. Therefore, I suggest that you publish one new major version using v7 and immediately target v8 afterwards, since judging from this PR it seems like you want to upgrade to Dart 2.19.

Without the changes from https://github.com/angulardart-community/angular/pull/37 I'm seeing errors when trying to serve angular dart apps

```
$ webdev serve
[INFO] ../../../../../../.pub-cache/hosted/pub.dev/build_modules-4.0.6/lib/src/module_cache.dart:21:70: Error: The method 'toJson' isn't defined
[INFO] ../../../../../../.pub-cache/hosted/pub.dev/build_modules-4.0.6/lib/src/module_cache.dart:24:66: Error: The method 'toJson' isn't defined
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
[SEVERE] This is likely caused by a misconfigured builder definition.
[SEVERE] 
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup.<anonymous closure> (package:build_daemon/client.dart:79:21)
#1      _runUserCode (dart:async/stream_pipe.dart:11:23)
#2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1704:9)
#3      _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:268:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:27)
#12     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#16     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#17     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#18     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#19     _LineSplitterSink.close (dart:convert/line_splitter.dart:137:11)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#25     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#26     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#27     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#28     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#29     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
#30     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#31     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#35     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
#36     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
#37     _StreamController.close (dart:async/stream_controller.dart:630:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:2362:21)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#43     _StreamController._add (dart:async/stream_controller.dart:648:7)
#44     _StreamController.add (dart:async/stream_controller.dart:596:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1884:35)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1327:18)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

Do you have any ideas as to why that would be happening?

**Comment by GZGavinZhao** [comment]
@felangel This is an issue (dart-lang/build#3412) caused by some change in type inference in Dart 2.18, so I'd suggest for the `angular_bloc` with AngularDart v7, set Dart 2.17 as the constraint and test it with Dart 2.17. After that version, you can use Dart 2.19 with the later versions.

**Comment by felangel** [comment]
> @felangel This is an issue ([dart-lang/build#3412](https://github.com/dart-lang/build/issues/3412)) caused by some change in type inference in Dart 2.18, so I'd suggest for the `angular_bloc` with AngularDart v7, set Dart 2.17 as the constraint and test it with Dart 2.17. After that version, you can use Dart 2.19 with the later versions.

Thanks for the suggestion, I'll verify shortly 👍

**Comment by GZGavinZhao** [comment]
I opened a Docker container so I was able to verify that `build_runner` builds everything fine (i.e. the `toJson` error is gone), but there's no Chrome in the container, so I couldn't test the actual project, though judging from the code I think the tests will past in 2.17 as well.

**Pull request merged**
