### PR TITLE
Clean up snippets docs

### PR DESCRIPTION
**Pull request by zepfietje**
## Status
**READY**

## Breaking Changes
NO

## Description
This PR cleans up the documentation related to the extension snippets. GIFs have been removed since it's hard to keep them up to date.

Translations will still need to be added (issue creation is automated, right?).

### CODE REVIEW

**Comment by zepfietje** [comment]
@felangel can this be merged? `vscode_bloc` can then be updated to include the recently updated snippets.

**Comment by felangel** [comment]
> @felangel can this be merged? `vscode_bloc` can then be updated to include the recently updated snippets.

I think it's more friendly/useful to remove the descriptions and just have gifs for each snippet than to link to the snippets json. Thoughts? I know it's a lot of work but I'm wiling to remake the gifs 👍

**Comment by zepfietje** [comment]
> > @felangel can this be merged? `vscode_bloc` can then be updated to include the recently updated snippets.
> 
> I think it's more friendly/useful to remove the descriptions and just have gifs for each snippet than to link to the snippets json. Thoughts? I know it's a lot of work but I'm willing to remake the gifs 👍

I get the idea, but having a GIF for every single snippet does feel a bit redundant. However, if you'd like to make them, that's fine. If we decide to include GIFs for all snippets, we might consider adding some sort of automation (like with the translations) to ensure everything is kept up to date.

**Comment by felangel** [comment]
I've addressed this in https://github.com/felangel/bloc/commit/31af209a44fb559cb28e90a45840790a3084a764 👍

**Comment by zepfietje** [comment]
> I've addressed this in [31af209](https://github.com/felangel/bloc/commit/31af209a44fb559cb28e90a45840790a3084a764) 👍

Looks good! However, the docs also need to be updated just like the extension README.

**Pull request closed without merging**
