### PR TITLE
Russian translations for docs (check PR checklist for status)

### PR DESCRIPTION
**Pull request by basilex**
# PR

## Description

Russian documentation (translation)

## Checklist

- [X] README
- [X] Cover page
- [X] Sidebar
- Introduction
  - [X] Getting Started
  - [X] Why Bloc?
- Core Concepts
  - [X] bloc
  - [X] flutter_bloc
- [X] Architecture
- [X] Testing
- [X] Naming Conventions
- [x] FAQs
- Tutorials
  - Flutter
    - [X] Counter
    - [X] Timer
    - [X] Infinite List
    - [x] Login
    - [x] Weather
    - [x] Todos
    - [x] Firebase Login
    - [x] Firestore Todos
  - AngularDart
    - [x] Counter
  - Flutter + AngularDart
    - [x] Github Search
- Recipes
  - Flutter
    - [x] Show SnackBar
    - [x] Navigation
    - [x] Bloc Access
- Tools
  - Extensions
    - [x] IntelliJ
    - [x] VSCode

## Breaking Changes

NO

### CODE REVIEW

**Comment by basilex** [comment]
Doc tutorials: Login, Weather were translated.

**Comment by basilex** [comment]
Felix, original document docs/flutterfirebaselogintutorial.md has an internal link to docs/recipesbloclistener.md which is missing at all.

Here is the line from an original document [docs/flutterfirebaselogintutorial.md]:

1309: ?> **Tip:** Check out the [BlocListener Recipe](recipesbloclistener.md) for more details.

We've to decide, either we'll create missing document or omit this link?

Thanx!

**Comment by felangel** [comment]
> Felix, original document _docs/flutterfirebaselogintutorial.md_ has an internal link to docs/recipesbloclistener.md which is missing at all.
> 
> Here is the line from an original document _docs/flutterfirebaselogintutorial.md_:
> 
> **1309: ?> **Tip:** Check out the [BlocListener Recipe](recipesbloclistener.md) for more details.**
> 
> We've to decide, either we'll create missing document or omit this link?
> 
> Thanx!

Nice catch! I believe that should say `[SnackBar Recipe](recipesfluttershowsnackbar.md)`

**Comment by basilex** [comment]
Felix, it's make sense to move ru translations from 'IN PROGRESS' to the 'TESTING' stage.
Seems everything translated already, but needs to be verified again. Probably other person with russian background will make such attempt professionally :)

**Comment by felangel** [comment]
Going to merge because the translations look good to me and we can always open additional PRs to make minor adjustments as we need. Amazing work and thanks again! 🙏

**Pull request merged**
