### PR TITLE
Update Flutter version of CI

### PR DESCRIPTION
**Pull request by tenhobi**
## Status
**READY**

## Breaking Changes
NO

## Description
Update of Flutter version in the CI file

### CODE REVIEW

**Comment by tenhobi** [comment]
@felangel with the version 1.17.0 there are some changes to Flutter Material Theme API, like

image

**Comment by felangel** [comment]
Thanks for opening the PR! We need to update the examples to fix all of the deprecated theming issues.

**Comment by felangel** [comment]
I have them on a branch and can make the update shortly if you don’t have time.

**Comment by tenhobi** [comment]
Yea, I don't have time to make those changes tho, so feel free (or anyone else) to make this. 🙃

**Comment by felangel** [comment]
closing this branch and will reopen another PR shortly with all the updates 👍

**Pull request closed without merging**
