### PR TITLE
mv distinct, rm where(til opposite proven)

### PR DESCRIPTION
**Pull request by orsenkucher**
Code for [my comment](https://github.com/felangel/bloc/pull/1017#issuecomment-612026137)

Status: **IN DEVELOPMENT**

### CODE REVIEW

**Comment by felangel** [comment]
Hey @orsenkucher 👋
I think this is a duplicate of https://github.com/felangel/bloc/pull/1017. The only difference is you’ve removed the closed check altogether. I can try to validate that and apply that update to the other PR as needed 👍

**Comment by orsenkucher** [comment]
It's actually PR to branch of #1017 PR
Just wanted to show what I meant😄

> The only difference is you’ve removed the closed check altogether

Not the only difference, I also placed distinct logic between `transformEvents` and `transformTransitions`
Should I close it?

**Comment by orsenkucher** [comment]
And I did remove `closed` check to motivate us to write test for it 😉
Because I think its redundant

**Comment by felangel** [comment]
@orsenkucher ah oops I didn't realize it was into the branch 👍
Let's merge it then and I'll work out whether the `where` was necessary or not 😄

**Pull request merged**
