### PR TITLE
feat(flutter_infinite_list): use throttleTime instead of debounceTime

### PR DESCRIPTION
**Pull request by eRuaro**
## Status

**READY**

## Breaking Changes

NO

## Description

Changed line 26 on `post_bloc.dart` from `events.debounceTime` to `events.throttleTime`. Changed as well it's corresponding unit test and removed the `wait` parameter on line 59 in `post_bloc_test.dart`.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by felangel — APPROVED** [review]
Thanks so much for the contribution! I really appreciate it 💯 💙

**Comment by eRuaro** [comment]
> Thanks so much for the contribution! I really appreciate it 💯 💙

Awesome! Here's to more contributions! 🍻

**Comment by mHassan20896** [comment]
The method 'throttleTime' isn't defined for the type 'Stream'.
Try correcting the name to the name of an existing method, or defining a method named 'throttleTime'.

I am getting this error

**Comment by narcodico** [comment]
@mHassan20896 that operator is from `rxdart` so you need to import that package.

**Pull request merged**
