### PR TITLE
Remove unneeded imports

### PR DESCRIPTION
**Pull request by kevmoo**
New hint!

### CODE REVIEW

**Review by felangel — DISMISSED** [review]
Awesome, thanks @kevmoo! 🎉 
Why weren't these being reported by the analyzer and what did you run to detect them `dart fix --apply`?

**Comment by kevmoo** [comment]
@felangel – this is a BRAND new lint that's only on dev channel.

I don't think there's a quick fix for it – yet!

So you'll hit this when your tools update to latest. But it doesn't hurt to get a start now 😄

**Comment by felangel** [comment]
> @felangel – this is a BRAND new lint that's only on dev channel.
> 
> I don't think there's a quick fix for it – yet!
> 
> So you'll hit this when your tools update to latest. But it doesn't hurt to get a start now 😄

Nice, thanks so much! 💙

**Review by felangel — APPROVED** [review]
🚀

**Pull request merged**
